/**
 * ClawForge Server Spec — core data types and builders
 */

export interface ServerAgent {
  id: string;
  name: string;
  emoji?: string;
  role?: string;
  description?: string;
  systemPrompt?: string;
}

export interface ServerSkill {
  source?: string;
  name?: string;
}

export interface ServerRuntime {
  type: 'single' | 'multi' | 'minimal';
  model: {
    provider: string;
    model: string;
  };
}

export interface ServerSpec {
  specVersion: string;
  id: string;
  name: string;
  emoji?: string;
  description?: string;
  runtime: ServerRuntime;
  agents: ServerAgent[];
  skills: ServerSkill[];
  workspace: Record<string, string>;
  mesh?: {
    enabled: boolean;
    modalities?: string[];
    tier?: string;
  };
}

export interface ForgeState {
  emoji: string;
  name: string;
  runtime: 'single' | 'multi' | 'minimal';
  agents: Array<{ emoji: string; name: string; desc: string }>;
  skills: Set<string>;
  systemPrompt: string;
  files: Record<string, string>;
  model: string;
}

/**
 * Build a server spec from forge UI state
 */
export function buildSpec(state: ForgeState): ServerSpec {
  return {
    specVersion: '1.0',
    id: 'srv_' + Math.random().toString(36).slice(2, 10),
    name: state.name,
    emoji: state.emoji,
    runtime: {
      type: state.runtime,
      model: {
        provider: state.model.includes('/') ? state.model.split('/')[0] : 'openrouter',
        model: state.model,
      },
    },
    agents: state.agents.map((a, i) => ({
      id: i === 0 ? 'main' : a.name.toLowerCase().replace(/[^a-z0-9]/g, '') || `agent${i}`,
      name: a.name,
      emoji: a.emoji,
      role: i === 0 ? 'lead' : 'specialist',
      description: a.desc,
      ...(i === 0 && state.systemPrompt ? { systemPrompt: state.systemPrompt } : {}),
    })),
    skills: [...state.skills].map(s => ({ source: `builtin:${s}` })),
    workspace: { ...state.files },
  };
}

/**
 * Generate a valid OpenClaw gateway config (JSON5-compatible JSON)
 */
export function generateOpenClawConfig(spec: ServerSpec): string {
  const model = spec.runtime?.model?.model || 'anthropic/claude-sonnet-4';
  const config = {
    agents: {
      defaults: {
        model: { primary: model },
        workspace: './workspace',
      },
    },
    sessions: {
      defaults: {
        model: model,
      },
    },
  };
  return JSON.stringify(config, null, 2);
}

/**
 * Generate a setup script for the server
 */
export function generateSetupScript(spec: ServerSpec): string {
  return `#!/bin/bash
# ${spec.name} — Setup Script
# Generated by ClawForge (vibeclaw.dev)
set -e

echo "Setting up ${spec.name}..."

# Install OpenClaw if not present
if ! command -v openclaw &> /dev/null; then
  echo "Installing OpenClaw..."
  curl -fsSL https://openclaw.ai/install.sh | bash -s -- --no-onboard
fi

# Create workspace directory
mkdir -p workspace

# Copy config
mkdir -p ~/.openclaw
cp openclaw.json ~/.openclaw/openclaw.json

# Copy workspace files
for f in workspace/*; do
  [ -f "$f" ] && cp "$f" ~/.openclaw/workspace/
done

echo ""
echo "Done! Run: openclaw gateway start"
echo ""
`;
}

/**
 * Generate a README for the server package
 */
export function generateReadme(spec: ServerSpec): string {
  const agentList = (spec.agents || [])
    .map(a => `- **${a.name}** — ${a.description || a.role || ''}`)
    .join('\n');
  const skillList = (spec.skills || [])
    .map(s => `- ${(s.source || s.name || '').replace('builtin:', '')}`)
    .join('\n');

  return `# ${spec.name}

> Generated by [ClawForge](https://vibeclaw.dev/forge)

## Agents

${agentList}

## Skills

${skillList}

## Setup

\`\`\`bash
# Option 1: Run the setup script
chmod +x setup.sh && ./setup.sh

# Option 2: Manual
curl -fsSL https://openclaw.ai/install.sh | bash
cp openclaw.json ~/.openclaw/openclaw.json
cp workspace/* ~/.openclaw/workspace/
openclaw gateway start
\`\`\`
`;
}

/**
 * Create a slug from a server name
 */
export function specToSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'server';
}

/**
 * Build the full download package (file map)
 */
export function buildPackage(spec: ServerSpec): Record<string, string> {
  const files: Record<string, string> = {
    'openclaw.json': generateOpenClawConfig(spec),
    'setup.sh': generateSetupScript(spec),
    'README.md': generateReadme(spec),
    'server-spec.json': JSON.stringify(spec, null, 2),
  };

  const ws = spec.workspace || {};
  for (const [name, content] of Object.entries(ws)) {
    if (content) files[`workspace/${name}`] = content;
  }

  return files;
}

/**
 * Convert a forge spec to an OpenClaw flavour-compatible object
 * (used when previewing in the sandbox)
 */
export function specToFlavour(spec: ServerSpec) {
  return {
    id: 'forge-preview',
    name: spec.name || 'Custom Server',
    emoji: spec.emoji || '',
    description: 'ClawForge custom server',
    agents: (spec.agents || []).map(a => ({
      id: a.id,
      name: a.name,
      emoji: a.emoji || '',
      description: a.description || a.role || '',
    })),
    teams: [],
    skills: (spec.skills || []).map(s => ({
      name: s.source ? s.source.replace('builtin:', '') : s.name || 'unknown',
      emoji: '',
      description: '',
    })),
    systemPrompt: spec.agents?.[0]?.systemPrompt || '',
    workspace: spec.workspace || {},
  };
}
